name = "real-estate-ai-chatbot"
type = "javascript"
account_id = "13f32362fed3b124424e06dcdfa91d8"
workers_dev = false
route = ""
zone_id = ""
pages_build_output_dir = "frontend/public"

[env.production]
name = "real-estate-ai-chatbot"
routes = [{pattern = "real-estate-ai-chatbot.pages.dev", zone_name = "pages.dev"}]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["frontend/public/**/*.js", "frontend/public/**/*.html"]

[build.upload]
dir = "frontend/public"
